[package]
name = "forte"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.20"
eframe = "0.20"
proc-macro2 = "1.0.50"
midi-toolkit-rs = { git = "https://github.com/arduano/midi-toolkit-rs", rev = "4482d61" }
serde = "1.0.152"
xsynth-core = { git = "https://github.com/arduano/xsynth", rev = "c568321" }
xsynth-soundfonts = { git = "https://github.com/arduano/xsynth", rev = "c568321" }
egui_extras = "0.20"
egui_file = "0.7.0"
rand = "0.8.5"
num-format = "0.4.4"
crossbeam-channel = "0.5.6"
